apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  type : ClusterIP
  ports:
  - port: 3333
    targetPort : 8080
    protocol: TCP
    name: http
  selector:
    app: demo-app